services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: aulasegura-nestjs
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Madrid
    ports:
      - ${WEB_SERVER_PORT}:3000
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./apps/backend:/web
      - ./apps/backend/imageserver/images:/app/images
    networks:
      - aulasegura-network

  database:
    image: yobasystems/alpine-mariadb:11.4.9
    container_name: aulasegura-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - aulasegura-network

  phpmyadmin:
    image: phpmyadmin:apache
    container_name: aulasegura-phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 256M
      BLOWFISH_SECRET: ${BLOWFISH_SECRET}
    ports:
      - "8085:80"
    networks:
      - aulasegura-network

  imageserver:
    image: nginx:1.29.3-alpine
    container_name: aulasegura-nginx-images
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./apps/backend/imageserver/images:/srv/images:ro
      - ./apps/backend/imageserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - aulasegura-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: aulasegura-reactnative
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - aulasegura-network

volumes:
  mariadb_data:
    driver: local

networks:
  aulasegura-network:
    driver: bridge